server:
    port: 9090
    
spring:
    application:
        name: msvc-course
    config:
        import: optional:configserver:http//localhost:8080
    
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/courseDB
        username: postgre
        password: admin
    jpa:
        hibernate:
            ddl-auto: create
        database: postgresql
        database-platform: org.hibernate.dialect.PostgresSQLDialect

eureka:
    instance:
        hostname: localhost
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka